# Generated by Django 3.1.4 on 2020-12-27 18:10

import UserTracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserTracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='qr_code',
        ),
        migrations.AlterField(
            model_name='company',
            name='Logo',
            field=models.ImageField(blank=True, default='defaultlogo.jpg', null=True, upload_to=UserTracker.models.to_upload_company),
        ),
    ]
