# Generated by Django 3.1.4 on 2020-12-03 09:07

import UserTracker.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserTracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Logo', models.ImageField(default='defaultlogo.jpg', upload_to=UserTracker.models.to_upload_company)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='UserTracker.company'),
        ),
    ]
