# Generated by Django 3.1.4 on 2021-01-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserTracker', '0002_profile_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
