# Generated by Django 3.1.4 on 2020-12-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserTracker', '0002_auto_20201227_2310'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyBarGraph',
        ),
        migrations.AddField(
            model_name='company',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
