# Generated by Django 3.1.4 on 2020-12-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserTracker', '0004_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
