# Generated by Django 3.1.4 on 2020-12-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserTracker', '0004_auto_20201204_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='temperature',
            field=models.FloatField(default=0),
        ),
    ]
